// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqrT8YSHHcora-43pWJ9p1YIS10fCCnw',
    appId: '1:861855165093:web:10fcf9dbe90fb04dab7b4c',
    messagingSenderId: '861855165093',
    projectId: 'logd-fbb44',
    authDomain: 'logd-fbb44.firebaseapp.com',
    storageBucket: 'logd-fbb44.firebasestorage.app',
    measurementId: 'G-SF6ZNHB1J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5iyk71Px3nE7cXM0HEoLXLN9fMVxwqjU',
    appId: '1:861855165093:android:e7ffa98d9f9b9d80ab7b4c',
    messagingSenderId: '861855165093',
    projectId: 'logd-fbb44',
    storageBucket: 'logd-fbb44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSiwuuNwTEi1_xn790I6RKGa4EfNkiFxM',
    appId: '1:861855165093:ios:d55b83ea19e8141aab7b4c',
    messagingSenderId: '861855165093',
    projectId: 'logd-fbb44',
    storageBucket: 'logd-fbb44.firebasestorage.app',
    iosBundleId: 'com.example.logd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSiwuuNwTEi1_xn790I6RKGa4EfNkiFxM',
    appId: '1:861855165093:ios:d55b83ea19e8141aab7b4c',
    messagingSenderId: '861855165093',
    projectId: 'logd-fbb44',
    storageBucket: 'logd-fbb44.firebasestorage.app',
    iosBundleId: 'com.example.logd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGqrT8YSHHcora-43pWJ9p1YIS10fCCnw',
    appId: '1:861855165093:web:562807dc05ec0cc3ab7b4c',
    messagingSenderId: '861855165093',
    projectId: 'logd-fbb44',
    authDomain: 'logd-fbb44.firebaseapp.com',
    storageBucket: 'logd-fbb44.firebasestorage.app',
    measurementId: 'G-XPZL7KGRB9',
  );
}
